### ISSUE TITLE
ability to specify yarn version via attributes

### ISSUE THREAD

**Issue by aerodynamik** [usemarkup/chef-node#12]
it will be really cool to have such an option ;)

**Comment by gsdevme** [comment]
Hey, thats a fairly simple change, its installed via the package manager so should be pretty standard chef. I will take a quick look @aerodynamik

**Comment by gsdevme** [comment]
I've tagged https://github.com/usemarkup/chef-node/releases/tag/v2.3.0

**Comment by aerodynamik** [comment]
thanks, Gavin! already using it.
